### ISSUE TITLE
Documentation for Saving Full Pipeline

### ISSUE THREAD

**Issue by yeamusic21** [AlexIoannides/pipeliner#4]
First let me start off by saying great work!  This seems like some really cool stuff.  

One question though, I can't seem to find any documentation on how to save the pipeline (i.e. pipeline_func).  Will this work with saveRSD or any other model saving frameworks like PMML?

Thanks :)

**Comment by AlexIoannides** [comment]
Any method for saving an arbitrary R object will work for you here - there is no support for PMML at the moment.
