### ISSUE TITLE
Random effect in R pipeline confusion 

### ISSUE THREAD

**Issue by nikosmatsa** [AlexIoannides/pipeliner#5]
I want to make a pipeline in R using pipeliner library for random effect model which has formula 
 " conc ~ Time,random =~1|Subject "

But  I am confused how I can pass the "conc~Time" and the "random =~1|Subject" in the transform feature and response.

Any help? 
 

`
library(name) 
library(pipeliner)

data("Glucose")
head(Glucose)
formula(Glucose)

Time = factor(Glucose$Time)

data <- Glucose

lme_pipeline <- pipeline(
  data,
  
  transform_features(function(df) { 
    data.frame(Subject = Glucose$Subject)
  }),
 
  
  transform_response(function(df) {
    data.frame(conc = Glucose$conc)
  }),
  
  estimate_model(function(df) { 
    lme(conc ~ Time,random =~1|Subject,na.action=na.omit,data=df)
  }),
  inv_transform_response(function(df) { 
    data.frame(pred_conc = df$pred_model )
  })
)
lme_pipeline

`

**Comment by AlexIoannides** [comment]
Hi.

Bearing in mind that I don't have any experience with random effects models, why do you want to pass the model formula anywhere other than the `estimate_model` stage?
